eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:9080
          predicates:
            - Path=/api/v1/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/course/**